# Generated by Django 5.0.2 on 2024-02-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Talento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={},
        ),
    ]
