# Generated by Django 5.0 on 2024-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento', '0002_alter_jobposting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company_logos/'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='featured_image',
            field=models.ImageField(upload_to='images/job_images/'),
        ),
        migrations.AlterModelTable(
            name='jobposting',
            table=None,
        ),
    ]
